### ISSUE TITLE
adf copy support

### ISSUE THREAD

**Issue by dcutugno** [RobSmithDev/FloppyDriveBridge#10]
Great project, can you add support for this interface?
https://nickslabor.niteto.de/projekte/adf-copy-english/

**Comment by RobSmithDev** [comment]
Sure, but I’d need one of those devices and some documentation. If I can get both then absolutely (assuming it’s suitable and provides the right kind of data)On 11 Jul 2023, at 12:07, dcutugno ***@***.***> wrote:﻿
Great project, can you add support for this interface?
https://nickslabor.niteto.de/projekte/adf-copy-english/

**Comment by dcutugno** [comment]
Due to chip shortage it's not sold anymore at this moment, i can beta test and give some info if you need them, i can share my machine if you want like for example with teamviever
