### ISSUE TITLE
Trackloading or custom loading fails in WinUAE

### ISSUE THREAD

**Issue by pawpaw91** [RobSmithDev/FloppyDriveBridge#13]
While the ADF disk image is fully supported in WinUAE, it is not the case with a real floppy. Copying the image from the disk back to .adf makes it work again.
Tested with “Soccer Kid disk 1”(originally disk “0”) ECS, Greaseweazle v. 4.1 & latest WinUAE (x86, x64) with Floppybridge on two different machines, a PC running windows 10 and a laptop with windows 8.1.
The “Stalling” option choice in Floppybridge yields slightly better results, with Krisalis Software logo and a part of the intro being properly displayed. Then, the system is resetting.

**Comment by RobSmithDev** [comment]
Sadly not every disk will ever work.  You can try the newer 1.6 version (installed with DiskFlashback) and see if it fixes the issue.
